name: Release

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: write
  id-token: write
  attestations: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: sbom.cyclonedx.json
      - uses: actions/attest@v4
        with:
          subject-path: '${{ github.workspace }}'
          sbom-path: '${{ github.workspace }}/sbom.cyclonedx.json'